#!/usr/bin/env python3
"""Generate an AI-ready DevOps release summary.

Offline mode intentionally avoids external API calls so the script can run safely in CI.
Later, the same input can be sent to Amazon Bedrock, OpenAI, or an internal AI gateway.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def run_git_log() -> list[str]:
    try:
        output = subprocess.check_output(
            ["git", "log", "--oneline", "-8"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        return [line.strip() for line in output.splitlines() if line.strip()]
    except Exception:
        return ["Git history not available in this execution context."]


def detect_artifacts() -> dict[str, bool]:
    files = [p.name for p in Path.cwd().glob("**/*") if p.is_file()]
    return {
        "terraform_files": any(name.endswith(".tf") for name in files),
        "github_actions": any(".github" in str(p) and p.name.endswith((".yml", ".yaml")) for p in Path.cwd().glob("**/*")),
        "dockerfiles": any(name == "Dockerfile" for name in files),
        "sbom_files": any("sbom" in name.lower() for name in files),
        "sarif_reports": any(name.endswith(".sarif") for name in files),
    }


def build_summary() -> dict[str, object]:
    commits = run_git_log()
    artifacts = detect_artifacts()
    risk_notes = []

    if artifacts["terraform_files"]:
        risk_notes.append("Terraform changes should be reviewed with plan output before apply.")
    if artifacts["dockerfiles"]:
        risk_notes.append("Container images should be scanned before release.")
    if not artifacts["sbom_files"]:
        risk_notes.append("SBOM should be generated by CI and attached as an artifact.")

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "project": "three-tier-devops-aws",
        "recent_commits": commits,
        "detected_artifacts": artifacts,
        "release_risk_summary": risk_notes or ["No major release risks detected from local metadata."],
        "recommended_next_steps": [
            "Review GitHub Actions status.",
            "Review Terraform plan before infrastructure deployment.",
            "Review Trivy, CodeQL, and Checkov findings.",
            "Confirm CloudFront, ALB, ECS, and RDS health after release.",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["offline"], default="offline")
    parser.add_argument("--output", default="release-summary.json")
    args = parser.parse_args()

    summary = build_summary()
    Path(args.output).write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
